version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
      - ./scripts:/app/scripts
    depends_on:
      - redis
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    command: celery -A backend.tasks worker --loglevel=info
    volumes:
      - ./backend:/app/backend

  beat:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    command: celery -A backend.tasks beat --loglevel=info
    volumes:
      - ./backend:/app/backend

volumes:
  redis_data:
